[project]
name = "tone-shift"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "librosa>=0.11.0",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "torch>=2.8.0",
    "torchcrepe>=0.0.24",
]
